# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-25 13:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wazimap', '0008_auto_20170424_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_code', models.CharField(max_length=255)),
                ('publisher_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('source_note', models.TextField(blank=True)),
                ('topics', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[])),
                ('date', models.CharField(max_length=255)),
                ('decimal', models.IntegerField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=15, max_digits=36, null=True)),
                ('geo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wazimap.Geography')),
            ],
            options={
                'ordering': ['publisher_code'],
            },
        ),
        migrations.CreateModel(
            name='DataIndicatorPublisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataIndicatorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DataTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('indicators', models.ManyToManyField(to='hurumap.DataIndicator')),
            ],
        ),
        migrations.AddField(
            model_name='dataindicator',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hurumap.DataIndicatorPublisher'),
        ),
    ]
