# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-25 05:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', django.contrib.postgres.fields.jsonb.JSONField()),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('source_id', models.CharField(max_length=255)),
                ('source_name', models.CharField(max_length=255)),
                ('source_note', models.TextField()),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='DataIndicatorAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='dataindicator',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hurumap.DataIndicatorAuthor'),
        ),
    ]
