# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-25 19:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hurumap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIndicatorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('country', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date', models.CharField(max_length=255)),
                ('decimal', models.IntegerField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=15, max_digits=36, null=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hurumap.DataIndicator')),
            ],
        ),
    ]
