# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-09 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurumap', '0002_dataindicatorvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('indicators', models.ManyToManyField(to='hurumap.DataIndicator')),
            ],
        ),
    ]
