# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-16 20:17
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hurumap', '0002_auto_20180616_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataindicator',
            options={'ordering': ['publisher_code']},
        ),
    ]
