# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-09 15:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap', '0008_auto_20170424_1209'),
        ('hurumap', '0003_datatopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataindicator',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dataindicatorvalue',
            name='geo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wazimap.Geography'),
        ),
        migrations.AlterField(
            model_name='dataindicator',
            name='source',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataindicator',
            name='source_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataindicator',
            name='topics',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='dataindicatorauthor',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataindicatorvalue',
            name='author_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
