# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-26 09:46
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hurumap', '0004_auto_20180626_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataIndicatorValue',
        ),
    ]
