# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-26 15:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurumap', '0005_delete_dataindicatorvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataindicator',
            name='country',
        ),
        migrations.RemoveField(
            model_name='dataindicator',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dataindicator',
            name='decimal',
        ),
        migrations.RemoveField(
            model_name='dataindicator',
            name='geo',
        ),
        migrations.RemoveField(
            model_name='dataindicator',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dataindicator',
            name='source',
        ),
        migrations.RemoveField(
            model_name='dataindicator',
            name='source_note',
        ),
        migrations.RemoveField(
            model_name='dataindicator',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='dataindicator',
            name='value',
        ),
        migrations.AddField(
            model_name='dataindicator',
            name='data_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataindicator',
            name='process_prefs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataindicator',
            name='view',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataindicator',
            name='publisher_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dataindicator',
            name='publisher_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataindicator',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
