# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-28 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurumap', '0006_auto_20180626_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataindicator',
            name='raw_data_file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
