# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-01 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurumap', '0007_dataindicator_raw_data_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataindicator',
            options={'ordering': ['publisher_codes']},
        ),
        migrations.RenameField(
            model_name='dataindicator',
            old_name='publisher_code',
            new_name='publisher_codes',
        ),
        migrations.AddField(
            model_name='dataindicator',
            name='code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dataindicator',
            name='scraper',
            field=models.CharField(default=b'manual', max_length=255),
        ),
    ]
