# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-01 20:08
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurumap', '0008_auto_20180701_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataindicator',
            name='raw_data_file',
            field=models.FileField(blank=True, default=b'', upload_to=b'uploads'),
        ),
    ]
