# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurumap', '0009_auto_20180701_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataindicator',
            name='raw_data_file',
            field=models.FileField(blank=True, default='', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='dataindicator',
            name='scraper',
            field=models.CharField(default='manual', max_length=255),
        ),
    ]
