# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-02 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hurumap', '0010_port_python3_20190315_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataindicator',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='datatopic',
            name='indicators',
        ),
        migrations.DeleteModel(
            name='DataIndicator',
        ),
        migrations.DeleteModel(
            name='DataIndicatorPublisher',
        ),
        migrations.DeleteModel(
            name='DataTopic',
        ),
    ]
