# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-02 08:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wazimap', '0013_port_to_python3'),
        ('hurumap', '0011_auto_20190702_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbTableChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250, unique=True), help_text='Comma-separated ordered list of fields this table describes.', size=None)),
            ],
        ),
        migrations.CreateModel(
            name='TableField',
            fields=[
                ('dbtable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wazimap.DBTable')),
                ('fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150, unique=True), help_text='Comma-separated ordered list of fields this table describes.', size=None)),
            ],
            bases=('wazimap.dbtable',),
        ),
        migrations.AddField(
            model_name='dbtablechart',
            name='db_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wazimap.DBTable'),
        ),
    ]
