# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-02 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap', '0013_port_to_python3'),
        ('hurumap', '0012_auto_20190702_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablefield',
            name='dbtable_ptr',
        ),
        migrations.AddField(
            model_name='dbtablechart',
            name='chart',
            field=models.CharField(choices=[('column', 'Column'), ('histogram', 'Histogram'), ('line', 'Line'), ('grouped_coloumn', 'Grouped Column'), ('pie', 'Pie Chart')], default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TableField',
        ),
    ]
