# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-02 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap', '0013_port_to_python3'),
        ('hurumap', '0013_auto_20190702_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbtablechart',
            name='fields',
        ),
        migrations.AddField(
            model_name='dbtablechart',
            name='field_table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wazimap.FieldTable'),
            preserve_default=False,
        ),
    ]
