# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-02 14:03
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurumap', '0014_auto_20190702_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbtablechart',
            name='fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150, unique=True), default=list, help_text='Comma-separated fields to be included in chart. Choose one field for one Column, Histogram or Pie. And Choose two fields for grouped column', size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dbtablechart',
            name='chart',
            field=models.CharField(choices=[('column', 'Column'), ('histogram', 'Histogram'), ('line', 'Line'), ('grouped_column', 'Grouped Column'), ('pie', 'Pie Chart')], max_length=32),
        ),
    ]
