# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-22 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('hurumapadmin', '0002_auto_20180522_1115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPostPage',
            new_name='BlogPage',
        ),
        migrations.RemoveField(
            model_name='bloglistpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BlogListPage',
        ),
    ]
