# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-22 10:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('admin', '0004_blogindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
