version: "3.7"

services:
  db:
    image: postgres:9.5
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=hurumap
      - POSTGRES_PASSWORD=hurumap
      - POSTGRES_DB=hurumap
      - PGUSER=hurumap
      - PGPASSWORD=hurumap

  web:
    build:
      context: .
      target: ${DOCKERFILE_TARGET:-hurumap}
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./:/src/hurumap
    env_file:
      - .env.example