version: "3.7"

services:
  db:
    image: postgres:9.5
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=hurumap
      - POSTGRES_PASSWORD=hurumap
      - POSTGRES_DB=hurumap
      - PGUSER=hurumap
      - PGPASSWORD=hurumap

  web:
    build:
      context: .
      target: ${DOCKERFILE_TARGET:-hurumap-kenya}
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./:/src/hurumap
    environment:
      - DATABASE_URL=postgresql://hurumap:hurumap@db:5432/hurumap
      - DJANGO_SECRET_KEY=somethingsecret
      - HURUMAP_URL='http://localhost:8000'
      - HURUMAP_APP=hurumap_ke
      - PGHOST=db
      - PGDATABASE=hurumap
      - PGUSER=hurumap
      - PGPASSWORD=hurumap
      - PYTHONDONTWRITEBYTECODE="True"
      - USE_MAPIT=True
      - DJANGO_DEBUG=${DJANGO_DEBUG:-True} # For testing deploys
